version: "3.3"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - pg-gallery:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'gallery_user'
      POSTGRES_PASSWORD: 'g4113ry'
    ports:
      - "5432:5432"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pg-gallery:
